### ISSUE TITLE
Chapter by API

### ISSUE THREAD

**Issue by lblabr** [Davidj361/OBS-ChapterMarker#6]
Hey, i'm quite new to OBS and try to find the right setup for recording training and sport events. i need to mark szenes on the recording for later cut. the camera is placed on the roof and obs is running on a raspi. i would like to send mark requests by mobile phone (in the same wifi-network) is that possible (API request) ?

thanks in advance lars

**Comment by Davidj361** [comment]
Hi Lars, there is obs-websocket functionality.
To create a chapter via obs-websocket you can use `"ChapterMarker"`
https://obsproject.com/forum/resources/obs-websocket-remote-control-obs-studio-from-websockets.466/

I haven't used obs-websocket but was recommended by another person to add it in. Let me know how it goes for you.

**Comment by lblabr** [comment]
does ChapterMarker has an API on obs-websocket, i could not find, how to address ChapterMarker by websocket

**Comment by Davidj361** [comment]
You use the command "ChapterMarker" to create a marker for your video.
I updated the README to reflect this.

Here's a guide on how to send commands via obs-websocket: https://www.youtube.com/watch?v=4Lf0VTs14W4

You might want to re-read the README, I left some important information in the disclaimer such as needing 2x space for recording and being MKV only.
